### ISSUE TITLE
Add PlotJuggler to the log analysis docs

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/PX4-Devguide#747] opened 2019-02-21 08:51 UTC
Thanks to @bresch for showing me the awsome tool https://www.plotjuggler.io/ which now supports ulog as input format. I just gave it a try and it looks quite awsome as a much more performant and powerful alternative to flightplot.

I think we should add it to the docs to spread the word. When I get to it I can do that myself.

**Comment by bkueng** [comment] 2019-02-21 08:54
Already done! https://github.com/PX4/Devguide/pull/743 :)

**Comment by MaEtUgR** [comment] 2019-02-21 09:05
@bkueng Thanks for mentioning, I don't consider it done yet because:
- I don't know why but you don't find it listed anywhere right now. Shouldn't it be here? https://dev.px4.io/en/log/ulog_file_format.html#known-implementations I searched for `PlotJuggler` in all public docs before creating this issue.
- No screenshot, explanation or alike on https://docs.px4.io/en/log/flight_log_analysis.html
@hamishwillee already mentioned this here: https://github.com/PX4/Devguide/pull/743#issuecomment-464916808

**Comment by facontidavide** [comment] 2019-02-21 09:18
I will prepare a screenshot and some text to add to https://docs.px4.io/en/log/flight_log_analysis.html

**Comment by facontidavide** [comment] 2019-02-21 09:35
![image](https://user-images.githubusercontent.com/2822888/53158049-09c04080-35c3-11e9-956b-810603fa7920.png)

PlotJuggler is a Qt5 desktop application that allows users to easily visualize and analyze data expressed as time series. It supports ULog (.ulg) since version 2.1.3.

Key features:
- Intuitive drag&drop interface.
- Arrange your data in multiple plots, tabs or window.
- Once you arranged your data, save it into a "Layout" file to reload it multiple times.
- Process your data inside PlotJuggler itself, using custom "data transformations".

Find more information, source code and downloads at: https://github.com/facontidavide/PlotJuggler

**Comment by MaEtUgR** [comment] 2019-02-21 14:06
@facontidavide Perfect! Do you want to add the info to https://github.com/PX4/px4_user_guide/blob/master/en/log/flight_log_analysis.md with a pr yourself?
**EDIT:** The screenshot should go here: https://github.com/PX4/px4_user_guide/tree/master/assets/flight_log_analysis

**Comment by facontidavide** [comment] 2019-02-21 17:25
Pull request sent

**Comment by hamishwillee** [comment] 2019-02-22 00:10
@MaEtUgR et al, just FYI, this is in the Ulog page - see https://dev.px4.io/master/en/log/ulog_file_format.html#known-implementations

The problem is with our multi version docs system. Changes to the master branch are supposed to appear both in the root and in the /master tree - but for whatever reason this is not updating the root version. @dagar can you please investigate?

**Comment by hamishwillee** [comment] 2019-02-22 00:13
I'll close this, because there is no more action that is specific to this case.

@facontidavide Thanks for the user guide PR - will review shortly.

**Closed as completed by hamishwillee** 2019-02-22 00:13 UTC

**Comment by MaEtUgR** [comment] 2019-02-26 20:40
Thanks, it was here: https://github.com/PX4/px4_user_guide/pull/446 (I like to keep things referenced)
